version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: [ "./vendor/bin/phpunit" ]
