# Acme Widget Co - Shopping Basket Implementation

![CI](https://github.com/rzqdevgod/Shopping-Basket/workflows/CI/badge.svg)

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and test
        run: docker-compose up --build --exit-code-from app

      - name: Run PHPStan
        run: docker-compose run app ./vendor/bin/phpstan analyse