# Acme Widget Co - Shopping Basket Implementation

![CI](https://github.com/rzqdevgod/Shopping-Basket/workflows/CI/badge.svg)

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build containers
        run: docker-compose build --no-cache

      - name: Install dependencies
        run: docker-compose run --rm app composer install

      - name: Run tests
        run: docker-compose run --rm app ./vendor/bin/phpunit

      - name: Run PHPStan
        run: docker-compose run --rm app ./vendor/bin/phpstan analyse src tests